package br.edu.ifal.agorahub.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF1F3A5F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD6E4F5)
val OnPrimaryContainerLight = Color(0xFF0B1D33)
val SecondaryLight = Color(0xFF2E75B6)
val OnSecondaryLight = Color(0xFFFFFFFF)
val TertiaryLight = Color(0xFF1B5E20)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC8E6C9)
val OnTertiaryContainerLight = Color(0xFF0A2E0D)
val ErrorLight = Color(0xFFB3261E)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFF9DEDC)
val OnErrorContainerLight = Color(0xFF410E0B)
val BackgroundLight = Color(0xFFFAFBFD)
val OnBackgroundLight = Color(0xFF1A1C1E)
val SurfaceVariantLight = Color(0xFFE0E3EA)
val OnSurfaceVariantLight = Color(0xFF43474E)
val OutlineLight = Color(0xFF73777F)
val OutlineVariantLight = Color(0xFFC3C7CF)

val PrimaryDark = Color(0xFFA8C8F0)
val OnPrimaryDark = Color(0xFF0B1D33)
val PrimaryContainerDark = Color(0xFF28486F)
val OnPrimaryContainerDark = Color(0xFFD6E4F5)
val SecondaryDark = Color(0xFF9CC3EC)
val OnSecondaryDark = Color(0xFF0A2540)
val TertiaryDark = Color(0xFFA5D6A7)
val OnTertiaryDark = Color(0xFF0A2E0D)
val TertiaryContainerDark = Color(0xFF1E4D22)
val OnTertiaryContainerDark = Color(0xFFC8E6C9)
val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)
val BackgroundDark = Color(0xFF111418)
val OnBackgroundDark = Color(0xFFE2E2E6)
val SurfaceVariantDark = Color(0xFF2B3138)
val OnSurfaceVariantDark = Color(0xFFC3C7CF)
val OutlineDark = Color(0xFF8D9199)
val OutlineVariantDark = Color(0xFFE2E2E6)